### ISSUE TITLE
Uint8.t (256) to color

### ISSUE THREAD

**Issue by toastal** [marc-chevalier/ocolor#2]
Seems really strange that there isn’t a way to get colors by their actual int value & only a pile of ‘poorly named’ (wasn’t this library’s fault but `snow[1-4]` isn’t descriptive) strings.

I was starting to create a patch to email the maintainer, but I realized very early that values like `0x01` were already missing (seen here as ‘maroon’ here https://www.ditig.com/256-colors-cheat-sheet …which doesn’t match this library’s ‘maroon’).

**Comment by marc-chevalier** [comment]
I'm not very sure what you mean by "actual value". I've tried to address this as much as possible with https://github.com/marc-chevalier/ocolor/commit/24e00eb7b4a6e01d94b4dde4e4816f3ab65f6fa6.
- we can build colors (4, 8 or 24 bits) as OCaml values and use them in formatting using the appropriate description (rgb for 24 bits)
- there are 3 modules for "standard" sets of names: Ocolor_x11, Ocolor_css, Ocolor_xterm (the 2 last ones being new). They allow you to convert x11, css or xterm names to rgb colors, and back. Xterm also has ids for its colors, so we can convert Xterm color names, xterm color ids, and rgb colors to each other.
- the color can be part of the format string, see `ocolor_format.mli` for examples, then we can specify colors by their x11 names and (newly) by their xterm or CSS names or xterm ids, using the above mentioned modules. We can also use the 4 (old stuff), 8 (6*6*6 cube + greyscale) or 24 bit (rgb) description.

In your case, I suspect you might be interested in:
```ocaml
Ocolor_xterm.color_of_id: int -> Ocolor_types.rgb option
```
or directly in a format string:
```ocaml
Ocolor_format.printf "@{<xterm:1>Something in this color@}"
Ocolor_format.printf "@{<xterm:0x01>Something in this color but in hexa@}"
Ocolor_format.printf "@{<xterm:maroon>Something in this color with a poetic name@}"
```

On the other hand, I'll stick to `int`, and not use `Uint8.t`: I have nothing against stdint, but I'd rather save a dep for one usage (each dep I add is a dep for every user of this lib) and if the user is not using stdint, or other kind of integers, it just makes things more complicated. While every integer should be easily convertible to the standard `int`. I'll add a Uint8.t version of ids if they ever make their way into the standard lib, but without removing the simple int version. The Uint8.t version of these conversions would then have the advantage of returning a non-optional value.

---

Before this commit, we could still have done, in a programmatic way:
```ocaml
Ocolor_format.printf "%aSomething in this color@}" Ocolor_format.pp_open_style Ocolor_types.(Fg (C4 red));
Ocolor_format.printf "%aSomething in this color@}" Ocolor_format.pp_open_style Ocolor_types.(Fg (C4 {r4=true; g4=true; b4=true; intensity4=false}));
Ocolor_format.printf "%aSomething in this color@}" Ocolor_format.pp_open_style Ocolor_types.(Fg (C24 {r24=128; g24=128; b24=128}))
```
in a literal way:
```ocaml
Ocolor_format.printf "@{<red>Something in this color@}"
(* no other way to specify 4 bits colors since they are very few *)
Ocolor_format.printf "@{<rgb(128,128,128)>Something in this color@}"
```

And to connect everything:
```ocaml
match Ocolor_xterm.color_of_id 0x01 with
| None -> assert false (* Absurd: whatever you want *)
| Some (r24, g24, b24) -> Ocolor_format.printf "%a" Ocolor_format.pp_open_style Ocolor_types.(Fg (C24 {r24; g24; b24}))
```
For instance! You may want to write your own `int (*XTerm id*) -> Ocolor_types.style` helper. For instance:
```ocaml
let style_of_xterm_id id =
  match Ocolor_xterm.color_of_id id with
  | None -> assert false (* Error handling: whatever you want *)
  | Some (r24, g24, b24) -> Ocolor_types.(Fg (C24 {r24; g24; b24}))

let () = Ocolor_format.printf "%aSomething in this color@}" Ocolor_format.pp_open_style (style_of_xterm_id 0x01)
```
I hope it helps.
